version: '2'

services:

  register-api:
    build:
      context: ./register-api
    container_name: register-api
    volumes:
      - ./var/log:/var/log
    ports:
      - "8080:8080"
    networks:
      - register-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://register-db:5432/register
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10 

networks:
     register-network:
          driver: bridge